=== Toniprni/harmony-smp/domibus/modules/domibus-distribution/src/test/resources/domibus-integration-test-server-config/tomcat/conf/domibus/pmodes/pmodes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema version="1.0"
        xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.e-codex.eu/domibus/pmodes/0.1"
        xmlns:tns="http://www.e-codex.eu/domibus/pmodes/0.1"
        elementFormDefault="qualified">

    <element name="PModes" type="tns:PModePoolType">
        <key name="PModeKey">
            <selector xpath="tns:PMode"/>
            <field xpath="@name"/>
        </key>
        <key name="BindingKey">
            <selector xpath="tns:Binding"/>
            <field xpath="@name"/>
        </key>
        <key name="UserServiceKey">
            <selector xpath="tns:UserService"/>
            <field xpath="@name"/>
        </key>
        <key name="ProducerKey">
            <selector xpath="tns:Producer"/>
            <field xpath="@name"/>
        </key>
        <keyref name="PModeToBindingKeyRef" refer="tns:BindingKey">
            <selector xpath="tns:PMode"/>
            <field xpath="@binding"/>
        </keyref>
        <keyref name="LegToUserServiceKeyRef" refer="tns:UserServiceKey">
            <selector xpath="tns:Binding/tns:MEP/tns:Leg | tns:PMode/tns:Binding/tns:MEP/tns:Leg"/>
            <field xpath="@userService"/>
        </keyref>
        <keyref name="LegToProducerKeyRef" refer="tns:ProducerKey">
            <selector xpath="tns:Binding/tns:MEP/tns:Leg | tns:PMode/tns:Binding/tns:MEP/tns:Leg"/>
            <field xpath="@producer"/>
        </keyref>
    </element>

    <complexType name="As4ReceiptType">
        <sequence>
            <element name="As4Reliability" minOccurs="0"/>
        </sequence>
        <attribute name="receiptTo" type="anyURI"/>
        <attribute name="deliverySemantics" default="Received">
            <simpleType>
                <restriction base="NMTOKEN">
                    <enumeration value="Received"/>
                    <enumeration value="Downloaded"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="method" default="Callback">
            <simpleType>
                <restriction base="NMTOKEN">
                    <enumeration value="Response"/>
                    <enumeration value="Callback"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="nonRepudiation" type="boolean" default="false"/>
    </complexType>

    <complexType name="As4ReliabilityType">
        <attribute name="maxRetries" type="unsignedInt"/>
        <attribute name="interval" type="unsignedInt"/>
        <attribute name="shutdown" type="unsignedInt"/>
        <attribute name="duplicateElimination" type="boolean" default="true"/>
        <attribute name="exponentialBackoff" type="boolean" default="false"/>
        <attribute name="randomize" type="boolean" default="false"/>
    </complexType>

    <complexType name="AuthorizationType">
        <attribute name="type" type="token" use="required"/>
        <attribute name="username" type="token"/>
        <attribute name="password" type="token"/>
    </complexType>

    <complexType name="BindingType">
        <sequence>
            <element name="MEP" type="tns:MEPType">
                <unique name="LegUniqueKey">
                    <selector xpath="tns:LegType"/>
                    <field xpath="@number"/>
                </unique>
            </element>
        </sequence>
        <attribute name="name" type="NMTOKEN"/>
    </complexType>

    <complexType name="CollaborationInfoType">
        <sequence>
            <element name="Service" type="tns:ServiceType"/>
            <element name="Action" type="string"/>
        </sequence>
    </complexType>

    <complexType name="EndpointType">
        <attribute name="address" type="string" use="required"/>
        <attribute name="soapVersion">
            <simpleType>
                <restriction base="token">
                    <enumeration value="1.1"/>
                    <enumeration value="1.2"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <complexType name="ErrorAtReceiverType">
        <attribute name="notifyProducer" type="boolean" default="false"/>
        <attribute name="notifyConsumer" type="boolean" default="false"/>
    </complexType>

    <complexType name="ErrorAtSenderType">
        <attribute name="notifyProducer" type="boolean" default="false"/>
        <attribute name="notifyConsumer" type="boolean" default="false"/>
        <attribute name="reportTo" type="anyURI"/>
    </complexType>

    <complexType name="LegType">
        <sequence>
            <element name="Endpoint" type="tns:EndpointType" minOccurs="0"/>
            <element name="ErrorAtSender" type="tns:ErrorAtSenderType" minOccurs="0"/>
            <element name="ErrorAtReceiver" type="tns:ErrorAtReceiverType" minOccurs="0"/>
            <element name="Authorization" type="tns:AuthorizationType" minOccurs="0"/>
            <element name="As4Receipt" type="tns:As4ReceiptType" minOccurs="0"/>
        </sequence>
        <attribute name="number">
            <simpleType>
                <restriction base="unsignedInt">
                    <minInclusive value="1"/>
                    <maxInclusive value="2"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="userService" type="NMTOKEN"/>
        <attribute name="producer" type="NMTOKEN"/>
        <attribute name="binding" type="NMTOKEN"/>
        <attribute name="security" type="NMTOKEN"/>
        <attribute name="reliability" type="NMTOKEN" use="prohibited"/>
        <attribute name="messageLabel" type="string"/>
        <attribute name="mpc" type="string"/>
        <attribute name="soapAction" type="string"/>
        <attribute name="wsaAction" type="string"/>
    </complexType>

    <complexType name="MEPType">
        <sequence>
            <element name="Leg" type="tns:LegType" maxOccurs="2"/>
        </sequence>
        <attribute name="name">
            <simpleType>
                <restriction base="string">
                    <enumeration value="One-Way/Push"/>
                    <enumeration value="One-Way/Pull"/>
                    <enumeration value="Two-Way/Sync"/>
                    <enumeration value="Two-Way/Push-and-Push"/>
                    <enumeration value="Two-Way/Push-and-Pull"/>
                    <enumeration value="Two-Way/Pull-and-Push"/>
                    <enumeration value="Two-Way/Pull-and-Pull"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <complexType name="MessagePayloadType">
        <sequence>
            <element name="SoapBodySchema" type="anyURI" minOccurs="0"/>
            <element name="Part" type="tns:PartType" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="label" type="NMTOKEN"/>
        <attribute name="maxSize" type="unsignedLong"/>
    </complexType>

    <complexType name="MessagePropertiesType">
        <sequence>
            <element name="Property" type="tns:PropertyType" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="PartType">
        <attribute name="cid" type="string" use="required"/>
        <attribute name="mimeType" type="token"/>
        <attribute name="schemaLocation" type="anyURI"/>
        <attribute name="description" type="string"/>
    </complexType>

    <complexType name="PartyIdType">
        <simpleContent>
            <extension base="string">
                <attribute name="type" type="token"/>
            </extension>
        </simpleContent>
    </complexType>

    <complexType name="PayloadInfoType">
        <sequence>
            <element name="Message" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="PModeType">
        <choice minOccurs="0" maxOccurs="unbounded">
            <element name="Binding" type="tns:BindingType"/>
            <element name="UserService" type="tns:UserServiceType"/>
            <element name="Producer" type="tns:ProducerType"/>
        </choice>
        <attribute name="name" type="NMTOKEN" use="required"/>
        <attribute name="binding" type="NMTOKEN"/>
        <attribute name="explicit" type="boolean" default="false"/>
    </complexType>

    <complexType name="PModePoolType">
        <choice minOccurs="0" maxOccurs="unbounded">
            <element name="PMode" type="tns:PModeType"/>
            <element name="Binding" type="tns:BindingType"/>
            <element name="UserService" type="tns:UserServiceType"/>
            <element name="Producer" type="tns:ProducerType"/>
        </choice>
    </complexType>

    <complexType name="ProducerType">
        <sequence>
            <element name="PartyId" type="tns:PartyIdType" maxOccurs="unbounded"/>
            <element name="Role" type="string"/>
        </sequence>
        <attribute name="name" type="NMTOKEN"/>
    </complexType>

    <complexType name="PropertyType">
        <attribute name="name" type="NMTOKEN" use="required"/>
        <attribute name="type" type="token"/>
        <attribute name="description" type="string"/>
        <attribute name="required" type="boolean" default="false"/>
    </complexType>

    <complexType name="ServiceType">
        <simpleContent>
            <extension base="string">
                <attribute name="type" type="token"/>
            </extension>
        </simpleContent>
    </complexType>

    <complexType name="ToPartyInfoType">
        <sequence>
            <element name="PartyId" type="tns:PartyIdType" maxOccurs="unbounded"/>
            <element name="Role" type="string"/>
        </sequence>
        <attribute name="name" type="NMTOKEN"/>
    </complexType>

    <complexType name="UserServiceType">
        <sequence>
            <element name="ToPartyInfo" type="tns:ToPartyInfoType"/>
            <element name="CollaborationInfo" type="tns:CollaborationInfoType"/>
            <element name="MessageProperties" type="tns:MessagePropertiesType" minOccurs="0"/>
            <element name="PayloadInfo" type="tns:PayloadInfoType" minOccurs="0"/>
        </sequence>
        <attribute name="name" type="NMTOKEN"/>
        <attribute name="maxPayloadsSize" type="long"/>
    </complexType>

</schema>

=== Toniprni/harmony-smp/domibus/modules/domibus-ebms3/src/test/resources/compression/test_pmodes/PMode_compression_disabled_empty_correct.xml
<?xml version="1.0" encoding="utf-8"?>

<tns:PModes xmlns:tns="http://www.e-codex.eu/domibus/pmodes/0.1"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.e-codex.eu/domibus/pmodes/0.1 pmodes.xsd">

    <tns:Producer name="GW2-GW">
        <tns:PartyId type="urn:oasis:names:tc:ebcore:partyid-type:iso3166-1">GW2</tns:PartyId>
        <tns:Role>GW</tns:Role>
    </tns:Producer>
    <tns:Producer name="GW1-GW">
        <tns:PartyId type="urn:oasis:names:tc:ebcore:partyid-type:iso3166-1">GW1</tns:PartyId>
        <tns:Role>GW</tns:Role>
    </tns:Producer>

    <tns:UserService name="COMPRESSION_EMPTY-GW">
        <tns:ToPartyInfo>
            <tns:PartyId type="urn:oasis:names:tc:ebcore:partyid-type:iso3166-1">GW2</tns:PartyId>
            <tns:Role>GW</tns:Role>
        </tns:ToPartyInfo>
        <tns:CollaborationInfo>
            <tns:Service>COMPRESSION</tns:Service>
            <tns:Action>EMPTY</tns:Action>
        </tns:CollaborationInfo>
    </tns:UserService>

    <tns:Binding name="COMPRESSION_EMPTY">
        <tns:MEP name="One-Way/Push">
            <tns:Leg number="1" producer="GW1-GW"
                     mpc="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/defaultMPC"
                     userService="COMPRESSION_EMPTY-GW"
                     security="sign-body-header_GW2_GW1">
                <tns:Endpoint
                        address="http://www.e-codex.eu"
                        soapVersion="1.2"/>
                <tns:PayloadService>
                    <tns:CompressionType></tns:CompressionType>
                </tns:PayloadService>
            </tns:Leg>
        </tns:MEP>
    </tns:Binding>

    <tns:PMode name="COMPRESSION_EMPTY" binding="COMPRESSION_EMPTY"/>


</tns:PModes>

=== Toniprni/harmony-smp/domibus/modules/domibus-distribution/src/test/resources/domibus-integration-test-server-config/tomcat/conf/domibus/pmodes/TESTGW1_TESTGW2.pmode.xml
<?xml version="1.0" encoding="utf-8"?>
<tns:PModes xmlns:tns="http://www.e-codex.eu/domibus/pmodes/0.1"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.e-codex.eu/domibus/pmodes/0.1 pmodes.xsd">
	<!--
         ************* 
         Producers. A producer represents an entity
         (person, application, corporation, etc...) that produces User Messages. A User Message is
         simply a message that contains payload data, and therefore, it is intended to be consumed
         by some entity that is beyond the MSH (i.e. sitting behind the MSH). A User Message always
         contains in its SOAP Header the element <eb:UserMessage>. A Producer is
         OPTIONAL. This means that the PMode could be used by many types of senders. When a sender
         uses this PMode to send out a message, the sender must therefore tell the MSH about its
         <eb:From> party. This is a way to share the same PMode with multiple
         different senders. If the PMode has to be used by a single specific sender, a
         <Producer> element MUST be declared; each element <Leg> must
         point to a <Producer> element. 
         ************* 
      -->
	<tns:Producer name="TESTGW1-GW">
		<tns:PartyId type="urn:oasis:names:tc:ebcore:partyid-type:iso3166-1">TESTGW1</tns:PartyId>
		<tns:Role>GW</tns:Role>
	</tns:Producer>
	<!--
          *************
          UserServices. A UserService represents the
          destination where the User Message will go. In the ebXML specification, this is represented
          by the xml elements <eb:To>, <eb:CollaborationInfo>,
          <eb:PayloadInfo> and <eb:MessageProperties>.
          *************
       -->
	<tns:UserService name="Invalid_endpoint_TESTGW2">
		<tns:ToPartyInfo>
			<tns:PartyId type="urn:oasis:names:tc:ebcore:partyid-type:iso3166-1">TESTGW2</tns:PartyId>
			<tns:Role>GW</tns:Role>
		</tns:ToPartyInfo>
		<tns:CollaborationInfo>
			<tns:Service>TEST</tns:Service>
			<tns:Action>invalid_endpoint</tns:Action>
		</tns:CollaborationInfo>
	</tns:UserService>
	<tns:UserService name="Unreliable_maxPayloadMin_TESTGW2" maxPayloadSize="1">
		<tns:ToPartyInfo>
			<tns:PartyId type="urn:oasis:names:tc:ebcore:partyid-type:iso3166-1">TESTGW2</tns:PartyId>
			<tns:Role>GW</tns:Role>
		</tns:ToPartyInfo>
		<tns:CollaborationInfo>
			<tns:Service>TEST</tns:Service>
			<tns:Action>unreliable_maxPayloadMin</tns:Action>
		</tns:CollaborationInfo>
	</tns:UserService>
	<tns:UserService name="Unreliable_TESTGW2">
		<tns:ToPartyInfo>
			<tns:PartyId type="urn:oasis:names:tc:ebcore:partyid-type:iso3166-1">TESTGW2</tns:PartyId>
			<tns:Role>GW</tns:Role>
		</tns:ToPartyInfo>
		<tns:CollaborationInfo>
			<tns:Service>TEST</tns:Service>
			<tns:Action>unreliable</tns:Action>
		</tns:CollaborationInfo>
	</tns:UserService>
	<tns:UserService name="As4_response_TESTGW2">
		<tns:ToPartyInfo>
			<tns:PartyId type="urn:oasis:names:tc:ebcore:partyid-type:iso3166-1">TESTGW2</tns:PartyId>
			<tns:Role>GW</tns:Role>
		</tns:ToPartyInfo>
		<tns:CollaborationInfo>
			<tns:Service>TEST</tns:Service>
			<tns:Action>as4_response</tns:Action>
		</tns:CollaborationInfo>
	</tns:UserService>
	<tns:UserService name="As4_callback_TESTGW2">
		<tns:ToPartyInfo>
			<tns:PartyId type="urn:oasis:names:tc:ebcore:partyid-type:iso3166-1">TESTGW2</tns:PartyId>
			<tns:Role>GW</tns:Role>
		</tns:ToPartyInfo>
		<tns:CollaborationInfo>
			<tns:Service>TEST</tns:Service>
			<tns:Action>as4_callback</tns:Action>
		</tns:CollaborationInfo>
	</tns:UserService>
	<tns:UserService name="As4_invalid_endpoint_TESTGW2">
		<tns:ToPartyInfo>
			<tns:PartyId type="urn:oasis:names:tc:ebcore:partyid-type:iso3166-1">TESTGW2</tns:PartyId>
			<tns:Role>GW</tns:Role>
		</tns:ToPartyInfo>
		<tns:CollaborationInfo>
			<tns:Service>TEST</tns:Service>
			<tns:Action>as4_invalid_endpoint</tns:Action>
		</tns:CollaborationInfo>
	</tns:UserService>
	<!--
          *************
          Bindings. A Binding contains information mostly
          related to transport, such as the URL address of the destination, the soap version, the
          soap action, and the MEP (Message Exchange Pattern) to use. The Binding element also
          contains detailed information of each leg of the MEP being used.
          *************
       -->
	<tns:Binding name="Binding_TESTGW1_TESTGW2_Unreliable">
		<tns:MEP name="One-Way/Push">
			<tns:Leg number="1" producer="TESTGW1-GW"
                     mpc="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/defaultMPC"
                     userService="Unreliable_TESTGW2"
                     security="sign-body-header_TESTGW1_TESTGW2">
				<tns:Endpoint
                        address="@domibus.testing.MSH.protocol@://@domibus.testing.MSH.host@:@domibus.testing.MSH.pt@/@domibus.testing.MSH.contextPath@"
                        soapVersion="1.2"/>
				<tns:As4Receipt nonRepudiation="false" method="response">
					<tns:As4Reliability duplicateElimination="true"/>
				</tns:As4Receipt>
			</tns:Leg>
		</tns:MEP>
	</tns:Binding>
	<tns:Binding name="Binding_TESTGW1_TESTGW2_As4_response">
		<tns:MEP name="One-Way/Push">
			<tns:Leg number="1" producer="TESTGW1-GW"
                     mpc="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/defaultMPC"
                     userService="As4_response_TESTGW2"
                     security="sign-body-header_TESTGW1_TESTGW2">
				<tns:Endpoint
                        address="@domibus.testing.MSH.protocol@://@domibus.testing.MSH.host@:@domibus.testing.MSH.pt@/@domibus.testing.MSH.contextPath@"
                        soapVersion="1.2"/>
				<tns:As4Receipt nonRepudiation="false" method="response">
					<tns:As4Reliability duplicateElimination="true"/>
				</tns:As4Receipt>
			</tns:Leg>
		</tns:MEP>
	</tns:Binding>
	<tns:Binding name="Binding_TESTGW1_TESTGW2_As4_callback">
		<tns:MEP name="One-Way/Push">
			<tns:Leg number="1" producer="TESTGW1-GW"
                     mpc="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/defaultMPC"
                     userService="As4_callback_TESTGW2"
                     security="sign-body-header_TESTGW1_TESTGW2">
				<tns:Endpoint
                        address="@domibus.testing.MSH.protocol@://@domibus.testing.MSH.host@:@domibus.testing.MSH.pt@/@domibus.testing.MSH.contextPath@"
                        soapVersion="1.2"/>
				<tns:As4Receipt nonRepudiation="false" method="callback">
					<tns:As4Reliability duplicateElimination="true"/>
				</tns:As4Receipt>
			</tns:Leg>
		</tns:MEP>
	</tns:Binding>
	<tns:Binding name="Binding_TESTGW1_TESTGW2_Invalid_endpoint">
		<tns:MEP name="One-Way/Push">
			<tns:Leg number="1" producer="TESTGW1-GW"
                     mpc="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/defaultMPC"
                     userService="Invalid_endpoint_TESTGW2"
                     security="sign-body-header_TESTGW1_TESTGW2">
				<tns:Endpoint
                        address="@domibus.testing.MSH.protocol@://@domibus.testing.MSH.host@:@domibus.testing.MSH.pt@/@domibus.testing.MSH.contextPath@"
                        soapVersion="1.2"/>
				<tns:As4Receipt nonRepudiation="false" method="response">
					<tns:As4Reliability duplicateElimination="true"/>
				</tns:As4Receipt>
			</tns:Leg>
		</tns:MEP>
	</tns:Binding>
	<tns:Binding name="Binding_TESTGW1_TESTGW2_As4_invalid_endpoint">
		<tns:MEP name="One-Way/Push">
			<tns:Leg number="1" producer="TESTGW1-GW"
                     mpc="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/defaultMPC"
                     userService="As4_invalid_endpoint_TESTGW2"
                     security="sign-body-header_TESTGW1_TESTGW2">
				<tns:Endpoint
                        address="@domibus.testing.MSH.protocol@://@domibus.testing.MSH.host@:@domibus.testing.MSH.pt@/@domibus.testing.MSH.contextPath@"
                        soapVersion="1.2"/>
				<tns:As4Receipt nonRepudiation="false" method="response">
					<tns:As4Reliability duplicateElimination="true"/>
				</tns:As4Receipt>
			</tns:Leg>
		</tns:MEP>
	</tns:Binding>
	<tns:Binding name="Binding_TESTGW1_TESTGW2_Unreliable_maxPayloadMin">
		<tns:MEP name="One-Way/Push">
			<tns:Leg number="1" producer="TESTGW1-GW"
                     mpc="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/defaultMPC"
                     userService="Unreliable_maxPayloadMin_TESTGW2"
                     security="sign-body-header_TESTGW1_TESTGW2">
				<tns:Endpoint
                        address="@domibus.testing.MSH.protocol@://@domibus.testing.MSH.host@:@domibus.testing.MSH.pt@/@domibus.testing.MSH.contextPath@"
                        soapVersion="1.2"/>
				<tns:As4Receipt nonRepudiation="false" method="response">
					<tns:As4Reliability duplicateElimination="true"/>
				</tns:As4Receipt>
			</tns:Leg>
		</tns:MEP>
	</tns:Binding>
	<!--
          *************
          PModes. A PMode (short for Processing Mode) is a
          concept introduced in the ebMS 3 core specifiction to deal with agreements. A Processing
          Mode always has one single Binding.
          *************
       -->
	<tns:PMode name="TESTGW1_TESTGW2_Unreliable" binding="Binding_TESTGW1_TESTGW2_Unreliable"/>
	<tns:PMode name="TESTGW1_TESTGW2_As4_response" binding="Binding_TESTGW1_TESTGW2_As4_response"/>	
	<tns:PMode name="TESTGW1_TESTGW2_As4_callback" binding="Binding_TESTGW1_TESTGW2_As4_callback"/>	
	<tns:PMode name="TESTGW1_TESTGW2_Invalid_endpoint" binding="Binding_TESTGW1_TESTGW2_Invalid_endpoint"/>	
	<tns:PMode name="TESTGW1_TESTGW2_As4_invalid_endpoint"
               binding="Binding_TESTGW1_TESTGW2_As4_invalid_endpoint"/>	
	<tns:PMode name="TESTGW1_TESTGW2_Unreliable_maxPayloadMin"
               binding="Binding_TESTGW1_TESTGW2_Unreliable_maxPayloadMin"/>

</tns:PModes>

=== Toniprni/harmony-smp/domibus/domibus/modules/domibus-distribution/src/test/resources/domibus-integration-test-server-config/tomcat/conf/domibus/pmodes/JMSTEST_GW2GW-s1.GW2.pmode.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- 
         ************* 
         This PModes file is for the consumer (partyId,role): 
         (GW1, GW)
         
         Service: JMSTEST
         
         Creation date/time: 2014-02-13T15:16:16.87+01:00 
         ************* 
      -->
<tns:PModes xmlns:tns="http://www.e-codex.eu/domibus/pmodes/0.1"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.e-codex.eu/domibus/pmodes/0.1 pmodes.xsd"><!--
         ************* 
         Producers. A producer represents an entity
         (person, application, corporation, etc...) that produces User Messages. A User Message is
         simply a message that contains payload data, and therefore, it is intended to be consumed
         by some entity that is beyond the MSH (i.e. sitting behind the MSH). A User Message always
         contains in its SOAP Header the element <eb:UserMessage>. A Producer is
         OPTIONAL. This means that the PMode could be used by many types of senders. When a sender
         uses this PMode to send out a message, the sender must therefore tell the MSH about its
         <eb:From> party. This is a way to share the same PMode with multiple
         different senders. If the PMode has to be used by a single specific sender, a
         <Producer> element MUST be declared; each element <Leg> must
         point to a <Producer> element. 
         ************* 
      -->
    <tns:Producer name="GW2-GW">
        <tns:PartyId type="urn:oasis:names:tc:ebcore:partyid-type:iso3166-1">GW2</tns:PartyId>
        <tns:Role>GW</tns:Role>
    </tns:Producer>
    <tns:Producer name="GW1-GW">
        <tns:PartyId type="urn:oasis:names:tc:ebcore:partyid-type:iso3166-1">GW1</tns:PartyId>
        <tns:Role>GW</tns:Role>
    </tns:Producer>
    <!--
          *************
          UserServices. A UserService represents the
          destination where the User Message will go. In the ebXML specification, this is represented
          by the xml elements <eb:To>, <eb:CollaborationInfo>,
          <eb:PayloadInfo> and <eb:MessageProperties>.
          *************
       -->
    <tns:UserService name="JMSTEST_UNRELIABLE_POSITIVE_GW1_GW">
        <tns:ToPartyInfo>
            <tns:PartyId type="urn:oasis:names:tc:ebcore:partyid-type:iso3166-1">GW1</tns:PartyId>
            <tns:Role>GW</tns:Role>
        </tns:ToPartyInfo>
        <tns:CollaborationInfo>
            <tns:Service>JMSTEST</tns:Service>
            <tns:Action>UNRELIABLE_POSITIVE</tns:Action>
        </tns:CollaborationInfo>
    </tns:UserService>

    <tns:UserService name="JMSTEST_UNRELIABLE_POSITIVE_GW2_GW">
        <tns:ToPartyInfo>
            <tns:PartyId type="urn:oasis:names:tc:ebcore:partyid-type:iso3166-1">GW2</tns:PartyId>
            <tns:Role>GW</tns:Role>
        </tns:ToPartyInfo>
        <tns:CollaborationInfo>
            <tns:Service>JMSTEST</tns:Service>
            <tns:Action>UNRELIABLE_POSITIVE</tns:Action>
        </tns:CollaborationInfo>
    </tns:UserService>

    <!--
          *************
          Bindings. A Binding contains information mostly
          related to transport, such as the URL address of the destination, the soap version, the
          soap action, and the MEP (Message Exchange Pattern) to use. The Binding element also
          contains detailed information of each leg of the MEP being used.
          *************
       -->
    <tns:Binding name="GW1_GW2_JMSTEST_UNRELIABLE_POSITIVE">
        <tns:MEP name="One-Way/Push">
            <tns:Leg number="1" producer="GW1-GW"
                     mpc="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/defaultMPC"
                     userService="JMSTEST_UNRELIABLE_POSITIVE_GW2_GW"
                     security="sign-body-header_GW1_GW2">
                <tns:Endpoint
                        address="@domibus.testing.MSH.protocol@://@domibus.testing.MSH.host@:@domibus.testing.MSH.pt@/@domibus.testing.MSH.contextPath@"
                        soapVersion="1.2"/>
            </tns:Leg>
        </tns:MEP>
    </tns:Binding>

    <tns:Binding name="GW2_GW1_JMSTEST_UNRELIABLE_POSITIVE">
        <tns:MEP name="One-Way/Push">
            <tns:Leg number="1" producer="GW2-GW"
                     mpc="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/defaultMPC"
                     userService="JMSTEST_UNRELIABLE_POSITIVE_GW1_GW"
                     security="sign-body-header_GW2_GW1">
                <tns:Endpoint
                        address="@domibus.module.ebms3.MSH.protocol@://@domibus.module.ebms3.MSH.host@:@domibus.module.ebms3.MSH.pt@/@domibus.module.ebms3.MSH.contextPath@"
                        soapVersion="1.2"/>
            </tns:Leg>
        </tns:MEP>
    </tns:Binding>

    <!--
          *************
          PModes. A PMode (short for Processing Mode) is a
          concept introduced in the ebMS 3 core specifiction to deal with agreements. A Processing
          Mode always has one single Binding.
          *************
       -->
    <tns:PMode name="GW1_GW2_JMSTEST_UNRELIABLE_POSITIVE" binding="GW1_GW2_JMSTEST_UNRELIABLE_POSITIVE"/>
    <tns:PMode name="GW2_GW1_JMSTEST_UNRELIABLE_POSITIVE" binding="GW2_GW1_JMSTEST_UNRELIABLE_POSITIVE"/>
    <!--
          *************
          This pmodes file is created by means of the PModes Toolkit 0.1
          Â© 2013 Land Nordrhein-Westfalen, Deutschland
          *************
       -->
</tns:PModes>
